apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genichi-ishii-pipeline-from-scratch
commonAnnotations:
  enzo: "true"
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: express-sample-app
  app.kubernetes.io/instance: express-sample-app-instance
  app.kubernetes.io/name: express-sample-app
